Add Offline Mode
jabardigitalservice/pikobar-rapidtest-checkin pull request #3
Opened 2021-01-21 02:40 UTC by jaluowen

- Menambahkan fitur offline mode
- Membuat helper untuk Shared Preference
- Membuat Dictionary
- Membuat global komponen TextField
- Menghapus file yang tidak terpakai

2021-01-21 02:41 UTC, jaluowen commented
Mohon bantuan review kang @aldiiii @gaganugraha33 @anandarh 
hampura banyak nextnya review per fitur aja ya biar sedikit seperti biasa :)

2021-01-22 04:14 UTC, anandarh requested changes

2021-01-22 04:14 UTC, anandarh commented on lib/blocs/kode_kegiatan/KodeKegiatanBloc.dart
> +            print(_page);
print

2021-01-22 04:14 UTC, anandarh commented on lib/blocs/offline/list_participants_offline/ListParticipantOfflineBloc.dart
> +        print(getSearch);
print

2021-01-22 04:14 UTC, anandarh commented on lib/blocs/offline/send_checkin_data/SendCheckinDataBloc.dart
> +        print(e.toString());
print

2021-01-22 04:14 UTC, anandarh commented on lib/blocs/offline/send_checkin_data/SendCheckinDataBloc.dart
> +                'Data berhasil terkirim ${startData.length - endDataError.length}/${startData.length}');
Ini state nya failure tapi pesan errornya kok `Data berhasil terkirim`, apakah memang seharusnya?

2021-01-22 04:14 UTC, anandarh commented on lib/main.dart
> +        title: 'PIKOBAR Tes Masif Checkin',
Dictionary

2021-01-26 08:41 UTC, jaluowen commented on lib/blocs/checkin/CheckinBloc.dart
> +                error: 'Kode registrasi tidak ditemukan dalam event ini');
Done @anandarh

2021-01-26 08:41 UTC, jaluowen commented on lib/blocs/checkin/CheckinBloc.dart
> +                      'Kode registrasi telah checkin pada ${unixTimeStampToDateTime(getName[0].attendedAt)}');
Done @anandarh

2021-01-26 08:41 UTC, jaluowen commented on lib/blocs/checkin/CheckinBloc.dart
> +                        'Kode lab telah digunakan oleh ${getLabCode[0].name}');
Done @anandarh

2021-01-26 08:41 UTC, jaluowen commented on lib/blocs/kode_kegiatan/KodeKegiatanBloc.dart
> +        print("jumlah data " + checkData.length.toString());
Done @anandarh

2021-01-26 08:41 UTC, jaluowen commented on lib/blocs/kode_kegiatan/KodeKegiatanBloc.dart
> +            print(_page);
Done @anandarh

2021-01-26 08:41 UTC, jaluowen commented on lib/blocs/offline/list_participants_offline/ListParticipantOfflineBloc.dart
> +        print(getSearch);
Done @anandarh

2021-01-26 08:41 UTC, jaluowen commented on lib/blocs/offline/send_checkin_data/SendCheckinDataBloc.dart
> +        print(e.toString());
Done @anandarh

2021-01-26 08:42 UTC, jaluowen commented on lib/main.dart
> +        title: 'PIKOBAR Tes Masif Checkin',
Done @anandarh

2021-01-26 08:44 UTC, jaluowen commented on lib/blocs/offline/send_checkin_data/SendCheckinDataBloc.dart
> +                'Data berhasil terkirim ${startData.length - endDataError.length}/${startData.length}');
Iya mas bram soalnya ini ngirim data pake bulk checkin jd ngirim banyak sekaligus, jadi yang dimunculinya data yang terkirim berapa dari jumlah datanya berapa begitu @anandarh

2021-01-28 03:09 UTC, anandarh approved these changes

2021-02-01 05:40 UTC, jaluowen commented
Minta tolong review mang @gaganugraha33 @aldiiii

2021-02-01 06:02 UTC, gaganugraha33 commented on lib/screen/login_screen.dart
> +                  // Center(child: Text('Atau')),
klo yang di comment ini masih di pake mang? @jaluowen

2021-02-01 06:07 UTC, jaluowen commented on lib/screen/login_screen.dart
> +                  // Center(child: Text('Atau')),
oh iya nanti di next review udah ilang mang, udah ada antrian baru buat di review nunggu ini dimerge dulu :)

2021-02-01 06:09 UTC, gaganugraha33 commented on lib/screen/login_screen.dart
> +                  // Center(child: Text('Atau')),
oke siapp, mang otw approve

2021-02-01 06:10 UTC, gaganugraha33 approved these changes

2021-02-01 06:12 UTC, merged